/**
 * backend/src/controllers/disputeController.ts
 * 
 * Dispute-related controller functions
 * Phase 7: Implement business logic for dispute handling
 */

import { Request, Response } from 'express';
import { fetchDispute, attachAISummary, saveEvidence } from '../services/disputeService';
import { generateDisputeSummary } from '../ai/aiEngine';

/**
 * openDispute
 * 
 * Purpose: Open a new dispute for a milestone
 * 
 * Phase 7 Implementation:
 * - Validate request body (projectAddress, milestoneId, reason, evidence metadata)
 * - Verify the caller is authorized (client or freelancer)
 * - Call smart contract's openDispute() function via ethers.js/viem
 * - Store dispute metadata in database (optional)
 * - Return transaction hash and dispute ID
 * 
 * Security:
 * - DO NOT handle private keys server-side
 * - User should sign transactions client-side
 * - Server only validates and facilitates the interaction
 */
export const openDispute = async (req: Request, res: Response): Promise<void> => {
  // TODO: Implement openDispute logic in Phase 7
  res.status(501).json({ error: 'Not implemented' });
};

/**
 * uploadEvidence
 * 
 * Purpose: Handle evidence file uploads for a dispute
 * 
 * Phase 7 Implementation:
 * - Validate uploaded files (req.files from multer middleware)
 * - Generate unique identifiers for each file
 * - Upload files to IPFS or decentralized storage
 * - Return IPFS hashes/CIDs for on-chain storage
 * - Clean up temporary local files after upload
 * - Optionally store file metadata in database
 * 
 * Security:
 * - Files already validated by multer middleware (type, size, count)
 * - Scan files for malware before IPFS upload (optional)
 * - DO NOT store sensitive data unencrypted
 */
export const uploadEvidence = async (req: Request, res: Response): Promise<void> => {
  try {
    // Extract disputeId from request body
    const { disputeId } = req.body;

    // Validate disputeId
    if (!disputeId || typeof disputeId !== 'string') {
      res.status(400).json({ error: 'Invalid or missing disputeId' });
      return;
    }

    // Validate that files were uploaded
    if (!req.files || !Array.isArray(req.files) || req.files.length === 0) {
      res.status(400).json({ error: 'No files uploaded' });
      return;
    }

    // Extract file paths from uploaded files
    // Store only file paths/names, NOT actual file data in memory
    const filePaths = (req.files as Express.Multer.File[]).map((file) => {
      // Use filename (generated by multer) as reference
      // TODO: Phase 7 - Upload to IPFS and use CID instead of local path
      return file.filename;
    });

    // Save evidence file references to dispute
    const updatedDispute = await saveEvidence(disputeId, filePaths);

    // Return list of saved file references
    res.status(200).json({
      disputeId,
      evidenceFiles: filePaths,
      totalFiles: filePaths.length,
      message: 'Evidence files uploaded successfully',
      dispute: {
        id: updatedDispute.id,
        evidenceCount: updatedDispute.evidenceHashes?.length || 0,
      },
    });
  } catch (error) {
    // Log error for debugging
    console.error('Error uploading evidence:', error);

    // Return safe error message
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    res.status(500).json({
      error: 'Failed to upload evidence',
      details: process.env.NODE_ENV === 'development' ? errorMessage : undefined,
    });
  }
};

/**
 * getDispute
 * 
 * Purpose: Retrieve dispute details by ID
 * 
 * Phase 7 Implementation:
 * - Extract dispute ID from req.params.id
 * - Query smart contract for on-chain dispute data
 * - Optionally fetch additional metadata from database
 * - Retrieve evidence files from IPFS if needed
 * - Return comprehensive dispute object with:
 *   - Milestone ID
 *   - Status (open, resolved, etc.)
 *   - Evidence hashes
 *   - Timestamps
 *   - Resolution outcome (if resolved)
 * 
 * Security:
 * - Validate dispute ID format
 * - Check if caller has permission to view dispute
 * - DO NOT expose private keys or sensitive contract data
 */
export const getDispute = async (req: Request, res: Response): Promise<void> => {
  // TODO: Implement getDispute logic in Phase 7
  res.status(501).json({ error: 'Not implemented' });
};

/**
 * generateAISummary
 * 
 * Purpose: Generate AI-powered analysis and recommendation for a dispute
 * 
 * Phase 7 Implementation:
 * - Extract dispute ID or evidence data from request body
 * - Fetch evidence files from IPFS
 * - Extract text/metadata from uploaded files (OCR for images, parse PDFs)
 * - Call AI service (e.g., OpenAI, Anthropic) with:
 *   - Dispute context (milestone details, evidence)
 *   - Prompt for fairness analysis
 *   - Request for resolution recommendation
 * - Parse AI response and structure output
 * - Return JSON with:
 *   - Summary of evidence
 *   - Recommended outcome (approve/reject/partial refund)
 *   - Confidence score
 *   - Reasoning explanation
 * 
 * Security:
 * - DO NOT expose API keys in client responses
 * - Validate and sanitize all inputs before AI processing
 * - Rate limit to prevent abuse
 * - DO NOT send private keys or wallet data to AI
 * - Consider privacy implications of sending user data to third-party AI
 */
export const generateAISummary = async (req: Request, res: Response): Promise<void> => {
  try {
    // Extract dispute ID from request body
    const { disputeId } = req.body;

    // Validate dispute ID
    if (!disputeId || typeof disputeId !== 'string') {
      res.status(400).json({ error: 'Invalid or missing disputeId' });
      return;
    }

    // Fetch dispute data from service layer
    // TODO: Phase 7 - Replace with real database query
    const dispute = await fetchDispute(disputeId);

    if (!dispute) {
      res.status(404).json({ error: 'Dispute not found' });
      return;
    }

    // Extract fields for AI analysis
    // TODO: Phase 7 - Fetch additional context (project details, milestone details)
    const projectDescription = dispute.projectDescription || 'No project description available';
    const milestoneDescription = dispute.milestoneDescription || 'No milestone description available';
    const clientStatement = dispute.reason || 'No client statement provided';
    const freelancerStatement = dispute.freelancerResponse || 'No freelancer response provided';
    
    // Use evidence file references (IPFS CIDs or file names), not full file data
    const evidenceFiles = dispute.evidenceHashes || [];

    // Call AI engine to generate summary
    const aiSummary = await generateDisputeSummary({
      projectDescription,
      milestoneDescription,
      clientStatement,
      freelancerStatement,
      evidenceFiles,
    });

    // Prepare summary data for storage
    const summaryData = {
      summary: aiSummary.summaryText,
      recommendation: aiSummary.suggestedOutcome,
      confidence: 0.85, // TODO: Phase 7 - Calculate or receive from AI
      reasoning: JSON.stringify({
        clientStrengths: aiSummary.clientStrengths,
        freelancerStrengths: aiSummary.freelancerStrengths,
        inconsistencies: aiSummary.inconsistencies,
      }),
    };

    // Save AI summary to dispute record
    // TODO: Phase 7 - Replace with real database update
    await attachAISummary(disputeId, summaryData);

    // Return AI summary to client
    res.status(200).json({
      disputeId,
      summary: aiSummary,
      message: 'AI summary generated successfully',
    });
  } catch (error) {
    // Log error for debugging (but don't expose details to client)
    console.error('Error generating AI summary:', error);

    // Return safe error message
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    res.status(500).json({
      error: 'Failed to generate AI summary',
      details: process.env.NODE_ENV === 'development' ? errorMessage : undefined,
    });
  }
};
